export RUN=/home/zpc/.sdkman/candidates/java/current/bin/native-image

export CP=/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/classes

export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/3.3.13/spring-boot-starter-data-jpa-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-aop/3.3.13/spring-boot-starter-aop-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-aop/6.1.21/spring-aop-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/aspectj/aspectjweaver/1.9.24/aspectjweaver-1.9.24.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/3.3.13/spring-boot-starter-jdbc-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/com/zaxxer/HikariCP/5.1.0/HikariCP-5.1.0.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-jdbc/6.1.21/spring-jdbc-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/hibernate/orm/hibernate-core/6.5.3.Final/hibernate-core-6.5.3.Final.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/transaction/jakarta.transaction-api/2.0.1/jakarta.transaction-api-2.0.1.jar
export CP=$CP:/home/zpc/.m2/repository/org/jboss/logging/jboss-logging/3.5.3.Final/jboss-logging-3.5.3.Final.jar
export CP=$CP:/home/zpc/.m2/repository/org/hibernate/common/hibernate-commons-annotations/6.0.6.Final/hibernate-commons-annotations-6.0.6.Final.jar
export CP=$CP:/home/zpc/.m2/repository/io/smallrye/jandex/3.1.2/jandex-3.1.2.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/classmate/1.7.0/classmate-1.7.0.jar
export CP=$CP:/home/zpc/.m2/repository/net/bytebuddy/byte-buddy/1.14.19/byte-buddy-1.14.19.jar
export CP=$CP:/home/zpc/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar
export CP=$CP:/home/zpc/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar
export CP=$CP:/home/zpc/.m2/repository/org/eclipse/angus/angus-activation/2.0.2/angus-activation-2.0.2.jar
export CP=$CP:/home/zpc/.m2/repository/org/glassfish/jaxb/txw2/4.0.5/txw2-4.0.5.jar
export CP=$CP:/home/zpc/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar
export CP=$CP:/home/zpc/.m2/repository/org/antlr/antlr4-runtime/4.13.0/antlr4-runtime-4.13.0.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/data/spring-data-jpa/3.3.13/spring-data-jpa-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/data/spring-data-commons/3.3.13/spring-data-commons-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-orm/6.1.21/spring-orm-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-context/6.1.21/spring-context-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-tx/6.1.21/spring-tx-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-beans/6.1.21/spring-beans-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar
export CP=$CP:/home/zpc/.m2/repository/org/slf4j/slf4j-api/2.0.17/slf4j-api-2.0.17.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-aspects/6.1.21/spring-aspects-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.3.13/spring-boot-starter-web-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter/3.3.13/spring-boot-starter-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.3.13/spring-boot-autoconfigure-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.3.13/spring-boot-starter-logging-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/ch/qos/logback/logback-classic/1.5.18/logback-classic-1.5.18.jar
export CP=$CP:/home/zpc/.m2/repository/ch/qos/logback/logback-core/1.5.18/logback-core-1.5.18.jar
export CP=$CP:/home/zpc/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.23.1/log4j-to-slf4j-2.23.1.jar
export CP=$CP:/home/zpc/.m2/repository/org/apache/logging/log4j/log4j-api/2.23.1/log4j-api-2.23.1.jar
export CP=$CP:/home/zpc/.m2/repository/org/slf4j/jul-to-slf4j/2.0.17/jul-to-slf4j-2.0.17.jar
export CP=$CP:/home/zpc/.m2/repository/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.3.13/spring-boot-starter-json-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.17.3/jackson-datatype-jdk8-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.17.3/jackson-datatype-jsr310-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.3.13/spring-boot-starter-tomcat-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.42/tomcat-embed-core-10.1.42.jar
export CP=$CP:/home/zpc/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.42/tomcat-embed-el-10.1.42.jar
export CP=$CP:/home/zpc/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.42/tomcat-embed-websocket-10.1.42.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-web/6.1.21/spring-web-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/io/micrometer/micrometer-observation/1.13.15/micrometer-observation-1.13.15.jar
export CP=$CP:/home/zpc/.m2/repository/io/micrometer/micrometer-commons/1.13.15/micrometer-commons-1.13.15.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-webmvc/6.1.21/spring-webmvc-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-expression/6.1.21/spring-expression-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot-docker-compose/3.3.13/spring-boot-docker-compose-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/boot/spring-boot/3.3.13/spring-boot-3.3.13.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.3/jackson-databind-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.17.3/jackson-annotations-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.17.3/jackson-core-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.17.3/jackson-module-parameter-names-2.17.3.jar
export CP=$CP:/home/zpc/.m2/repository/com/microsoft/sqlserver/mssql-jdbc/12.6.4.jre11/mssql-jdbc-12.6.4.jre11.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar
export CP=$CP:/home/zpc/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-core/6.1.21/spring-core-6.1.21.jar
export CP=$CP:/home/zpc/.m2/repository/org/springframework/spring-jcl/6.1.21/spring-jcl-6.1.21.jar

export OPTS="--no-fallback"
export OPTS="$OPTS -o /home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/bytebuddy-troubleshoot-native"
export OPTS="$OPTS -H:ConfigurationFileDirectories=/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.glassfish.jaxb/jaxb-runtime/3.0.2,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/ch.qos.logback/logback-classic/1.4.9,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.hibernate.orm/hibernate-core/6.5.0.Final,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.jboss.logging/jboss-logging/3.5.0.Final,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.fasterxml.jackson.core/jackson-databind/2.15.2,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.zaxxer/HikariCP/5.0.1,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.microsoft.sqlserver/mssql-jdbc/12.2.0.jre11,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.apache.tomcat.embed/tomcat-embed-core/10.0.20,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.glassfish.jaxb/jaxb-runtime/3.0.2,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/ch.qos.logback/logback-classic/1.4.9,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.hibernate.orm/hibernate-core/6.5.0.Final,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.jboss.logging/jboss-logging/3.5.0.Final,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.fasterxml.jackson.core/jackson-databind/2.15.2,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.zaxxer/HikariCP/5.0.1,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/com.microsoft.sqlserver/mssql-jdbc/12.2.0.jre11,/home/zpc/apps/graalvm/lab-graalvm-native-image/bytebuddy-troubleshoot/target/graalvm-reachability-metadata/f0427f39ee1740c9ef2de376d27f95e8a05ba2fd/org.apache.tomcat.embed/tomcat-embed-core/10.0.20"
export OPTS="$OPTS --no-fallback -H:+AddAllCharsets -H:+IncludeAllLocales"

$RUN -cp $CP $OPTS